### ISSUE TITLE
[QUESTION] Build on MacOS failed because MSG_NOSIGNAL macro redefined

### ISSUE THREAD

**Issue by ting3000** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#1002]
Executing "cmake .." from build directory failed on MacOS X11. The build output message below shows "MSG_NOSIGNAL macro redefined" error when building websockets_shared. Could somebody help please. Thanks!

===================================================
Scanning dependencies of target websockets_shared
[  1%] Building C object CMakeFiles/websockets_shared.dir/lib/core/alloc.c.o
In file included from /Users/tingzhaoadt.com/development/KinesisVideoStreaming/amazon-kinesis-video-streams-webrtc-sdk-c-master/open-source/libwebsockets/build/src/project_libwebsockets/lib/core/alloc.c:1:
In file included from /Users/tingzhaoadt.com/development/KinesisVideoStreaming/amazon-kinesis-video-streams-webrtc-sdk-c-master/open-source/libwebsockets/build/src/project_libwebsockets/lib/core/private.h:119:
/Users/tingzhaoadt.com/development/KinesisVideoStreaming/amazon-kinesis-video-streams-webrtc-sdk-c-master/open-source/libwebsockets/build/src/project_libwebsockets/lib/plat/unix/private.h:167:9: error: 'MSG_NOSIGNAL' macro redefined [-Werror,-Wmacro-redefined]
#define MSG_NOSIGNAL SO_NOSIGPIPE
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include/sys/socket.h:584:9: note: previous definition is here
#define MSG_NOSIGNAL    0x80000         /* do not generate SIGPIPE on EOF */
        ^
1 error generated.
make[5]: *** [CMakeFiles/websockets_shared.dir/lib/core/alloc.c.o] Error 1
make[4]: *** [CMakeFiles/websockets_shared.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [build/src/project_libwebsockets-stamp/project_libwebsockets-build] Error 2
make[1]: *** [CMakeFiles/project_libwebsockets.dir/all] Error 2
make: *** [all] Error 2
CMake Error at CMake/Utilities.cmake:65 (message):
  CMake step for libwebsockets failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:119 (build_dependency)

**Comment by MushMal** [comment]
I am not sure how you end up with this error. Clean building libWebSockets should have worked OK. Can you please confirm that you are building clean 

`git clean -ddfx`

Make sure you have the latest codebase and no modifications. 

run cmake .. from your build directory

**Comment by tingz2004** [comment]
I did fresh clean build. The issue seems to be similar to this post: https://github.com/netdata/netdata/pull/10333

**Comment by MushMal** [comment]
Which version of xCode you are using? Please provide more info and resolve this ticket

**Comment by tingz2004** [comment]
XCode is Version 12.2. The issue is from building the dependent libwebsockets. I can workaround it by by modifying the private.h file then build libwebsockets separately.
I can reproduce the issue by run cmake for a clean build which includes building libwebsockets as dependent.

**Comment by MushMal** [comment]
I have 11.3.1 and it works out of the gate without any modifications. The versions of the open source components we chose should work without any modifications. 

We should try to reproduce this issue and see what recommendation we can make for building the LWS. Perhaps the later versions have already fixed this issue (if we repro it). Moving to a new version is not something we should do without in-depth testing, etc..

**Comment by MushMal** [comment]
I can't seem to update my high sierra. Whats the OS version you are using?

**Comment by ting3000** [comment]
It is macOS 11.0.1

**Comment by MushMal** [comment]
This is likely a regression in the toolchains supplied by xCode which was fixed. I have the following versions of my toolchain

Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix

**Comment by disa6302** [comment]
@ting3000 , 

Do you have an update? There are some differences between xcode toolchain versions that could be a pain point. Have you tried with Apple LLVM version 10.0.1?

**Comment by hassanctech** [comment]
Closing due to staleness.

**Comment by jimfleming** [comment]
This is still an issue. Should I open a new issue for it? Downgrading LLVM to the specified version of 10.0.1 (installer won't proceed) is not possible on macOS 10.15.6. This PR on another repo appears to be a (hacky) fix: https://github.com/netdata/netdata/pull/10333/files#diff-b4ca64ef1b8154af7f400eaea8d86b883cba71679ac27d3a6d069cfaf9da5f1e

**Comment by allayli** [comment]
Actually,  libwebsockets fixed on later version
Ref:
https://github.com/warmcat/libwebsockets/commit/7b2ef3b19e61752ebde7c47ddb38a6d381befa13#diff-61262272ac91e9e6209bfc2ee62cf1dcd58e1cb130775fdb0c919f98450d80ac

But even change the change the version tag from v3.2.3 to v4.1.6 on libwebsockets-CMakeLists.txt, it does not work either.
Another error occurs
`
ld: library not found for -lssl
`

Thanks to the solution on
https://github.com/brianmario/mysql2/issues/795#issuecomment-337006164

FINALLY I built libwebsockets successfully 😃

**Comment by allayli** [comment]
Oh, too young too naive 😢 
make error occurs:
`
amazon-kinesis-video-streams-webrtc-sdk-c/src/source/Signaling/Signaling.c:98:18: error: no member named 'ws_ping_pong_interval'
`
due to 
https://github.com/warmcat/libwebsockets/commit/280c81278dcb88c074aa19cbf8de809e366a9ece

**Comment by allayli** [comment]
Hi all,

I fork the libwebsockets and cherry pick the fix from v4.1.x to v3.2.x

Change the 
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/CMake/Dependencies/libwebsockets-CMakeLists.txt

```
    GIT_REPOSITORY    https://github.com/allayli/libwebsockets.git
    GIT_TAG           v3.2.4
```

Hope that it resolve your problems.

**Comment by sb4brt** [comment]
This is still an issue. 
open-source/libwebsockets/build/src/project_libwebsockets/lib/plat/unix/./private-lib-plat-unix.h:186:9: error: 'MSG_NOSIGNAL' macro redefined [-Werror,-Wmacro-redefined]
#define MSG_NOSIGNAL SO_NOSIGPIPE
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/sys/socket.h:584:9: note: previous definition is here
#define MSG_NOSIGNAL    0x80000         /* do not generate SIGPIPE on EOF */
        ^
1 error generated.
make[5]: *** [lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-caps.c.o] Error 1
make[4]: *** [lib/CMakeFiles/websockets_shared.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [build/src/project_libwebsockets-stamp/project_libwebsockets-build] Error 2
make[1]: *** [CMakeFiles/project_libwebsockets.dir/all] Error 2
make: *** [all] Error 2
CMake Error at CMake/Utilities.cmake:65 (message):
  CMake step for libwebsockets failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:120 (build_dependency)

**Comment by allayli** [comment]
@sb4brt which version of libwebsockets are you using?

**Comment by sb4brt** [comment]
@allayli - It works fine if I use your version with the patch. Just bumping this thread so AWS knows this is still an issue so they can roll a fix into the mainline (the hope at least :) )

**Comment by hassanctech** [comment]
I'm re-opening this.  I just upgraded to MacOS to Catalina and I'm hitting the same issue.

**Comment by davidstl** [comment]
Facing this issue also. I have latest xcode and OSX version. Same error that sb4brt. So LWS doesn't work on mac anymore? If I build with cocoapods I have a different solution that works: SocketRocket

**Comment by sb4brt** [comment]
> Facing this issue also. I have latest xcode and OSX version. Same error that sb4brt. So LWS doesn't work on mac anymore? If I build with cocoapods I have a different solution that works: SocketRocket

If you use @allayli 's forked version above you can get it to work. I ran into issues where I had to run make multiple times and gstreamer couldn't find my webcam. If I was starting over, I would have just used Linux if it was an option :)

**Comment by disa6302** [comment]
Closing this issue since it is fixed now. `libwebsockets` version has also been updated on master.
